/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.4.0
 *
 * Project: 'PMRA_B2.Debug+GD32F303ZE' 
 * Target:  'Debug+GD32F303ZE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32f30x.h"

/* GigaDevice::Device:GD32F30x_StdPeripherals:EXTI@2.2.0 */
#define RTE_DEVICE_STDPERIPHERALS_EXTI
/* GigaDevice::Device:GD32F30x_StdPeripherals:GPIO@2.2.0 */
#define RTE_DEVICE_STDPERIPHERALS_GPIO
/* GigaDevice::Device:GD32F30x_StdPeripherals:MISC@2.2.0 */
#define RTE_DEVICE_STDPERIPHERALS_MISC
/* GigaDevice::Device:GD32F30x_StdPeripherals:PMU@2.2.0 */
#define RTE_DEVICE_STDPERIPHERALS_PMU
/* GigaDevice::Device:GD32F30x_StdPeripherals:RCU@2.2.0 */
#define RTE_DEVICE_STDPERIPHERALS_RCU
/* GigaDevice::Device:GD32F30x_StdPeripherals:USART@2.1.0 */
#define RTE_DEVICE_STDPERIPHERALS_USART


#endif /* RTE_COMPONENTS_H */
